config/routes.rb
Rails.application.routes.draw do
  resources :whatsapp_infos
  get 'whatsapp/index'
  post 'whatsapp/index'
  resources :contatos
  resources :boletins
  root to: "pages#index"
  #inicio
  get 'pages/index'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boletim.rb
class Boletim < ApplicationRecord
end

app/models/contato.rb
class Contato < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
enum status: [:ativo, :inativo]
enum local: [:produtos, :promoções]
has_one_attached :image #virtual não precisa estar no banco

validates :name, presence: true,:allow_nil => false
validates :valor, presence: true,:allow_nil => false 
validates :local, presence: true,:allow_nil => false 
validates :descricao, presence: true,:allow_nil => false 

default_scope {where(status: :ativo)}
scope :primeira_parte_em_produtos, -> { where(status: :ativo, local: :produtos).order(created_at: :desc).limit((Produto.count/2)+1)}
scope :segunda_parte_em_produtos, -> { where(status: :ativo, local: :produtos).order(created_at: :asc).limit(Produto.count/2)}
scope :em_promocao,-> { where(sttus: :ativo, local: :promocoes) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum tipo: [:cliente, :admin]
  enum status: [:ativo, :inativo]
 # has_many :produtos
end

app/models/whatsapp_info.rb
class WhatsappInfo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boletins_controller.rb
class BoletinsController < ApplicationController
  before_action :set_boletim, only: [:show, :edit, :update, :destroy]

  # def index
  #   @boletins = Boletim.all
  # end

  # def show
  # end

  # def new
  #   @boletim = Boletim.new
  # end

  # def edit
  # end

  def create
    @boletim = Boletim.new(boletim_params)
    respond_to do |format|
      if @boletim.save
        format.html { redirect_to root_path, :flash => { :success => "Seu e-mail foi cadastrado com sucesso!" }}
      else
        format.html { redirect_to root_path }
      end
    end
  end

  # def update
  #   respond_to do |format|
  #     if @boletim.update(boletim_params)
  #       format.html { redirect_to @boletim, notice: 'Boletim was successfully updated.' }
  #     else
  #       format.html { render :edit }
  #     end
  #   end
  # end

  def destroy
    @boletim.destroy
    respond_to do |format|
      format.html { redirect_to boletins_url, notice: 'Boletim criado com sucesso.' }
    end
  end

  private
    def set_boletim
      @boletim = Boletim.find(params[:id])
    end

    def boletim_params
      params.require(:boletim).permit(:email)
    end
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  before_action :set_contato, only: [:show, :edit, :update, :destroy]

  def index
    @contatos = Contato.all
  end

  def show
  end

  def new
    @contato = Contato.new
  end

  def edit
  end

  def create
    @contato = Contato.new(contato_params)
    respond_to do |format|
      if @contato.save
        format.html { redirect_to root_path, :flash => {:success => 'Contato enviado com sucesso, em breve retornaremos.' }}
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.html { redirect_to @contato, notice: 'Contato was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @contato.destroy
    respond_to do |format|
      format.html { redirect_to contatos_url, notice: 'Contato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_contato
      @contato = Contato.find(params[:id])
    end

    def contato_params
      params.require(:contato).permit(:nome, :email, :mensagem)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@primeira_parte_em_produtos = Produto.primeira_parte_em_produtos
  	@segunda_parte_em_produtos = Produto.segunda_parte_em_produtos
  	@produtos_em_promocao = Produto.em_promocao.order('random()').all
  end
end

app/controllers/whatsapp_controller.rb
class WhatsappController < ApplicationController
  def index
  	WhatsappHelper.whatsapp_envia_mensagem(params[:nome],params[:mensagem])
  	redirect_to root_path, :flash =>{:success => "mensagem enviada, logo retornaremos!"}
  end
end

app/controllers/whatsapp_infos_controller.rb
class WhatsappInfosController < ApplicationController
  before_action :set_whatsapp_info, only: [:show, :edit, :update, :destroy]

  # GET /whatsapp_infos
  # GET /whatsapp_infos.json
  def index
    @whatsapp_infos = WhatsappInfo.all
  end

  # GET /whatsapp_infos/1
  # GET /whatsapp_infos/1.json
  def show
  end

  # GET /whatsapp_infos/new
  def new
    @whatsapp_info = WhatsappInfo.new
  end

  # GET /whatsapp_infos/1/edit
  def edit
  end

  # POST /whatsapp_infos
  # POST /whatsapp_infos.json
  def create
    @whatsapp_info = WhatsappInfo.new(whatsapp_info_params)

    respond_to do |format|
      if @whatsapp_info.save
        format.html { redirect_to @whatsapp_info, notice: 'Whatsapp info was successfully created.' }
        format.json { render :show, status: :created, location: @whatsapp_info }
      else
        format.html { render :new }
        format.json { render json: @whatsapp_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /whatsapp_infos/1
  # PATCH/PUT /whatsapp_infos/1.json
  def update
    respond_to do |format|
      if @whatsapp_info.update(whatsapp_info_params)
        format.html { redirect_to @whatsapp_info, notice: 'Whatsapp info was successfully updated.' }
        format.json { render :show, status: :ok, location: @whatsapp_info }
      else
        format.html { render :edit }
        format.json { render json: @whatsapp_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /whatsapp_infos/1
  # DELETE /whatsapp_infos/1.json
  def destroy
    @whatsapp_info.destroy
    respond_to do |format|
      format.html { redirect_to whatsapp_infos_url, notice: 'Whatsapp info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_whatsapp_info
      @whatsapp_info = WhatsappInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def whatsapp_info_params
      params.require(:whatsapp_info).permit(:to)
    end
end

app/helpers/application_helper.rb
require 'twilio-ruby'
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert alert-#{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end

end

app/helpers/boletins_helper.rb
module BoletinsHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/whatsapp_helper.rb
require 'twilio-ruby'
module WhatsappHelper
  def self.whatsapp_envia_mensagem(nome,mensagem)
    # Your Account Sid and Auth Token from twilio.com/console
    account_sid = 'AC7188d3912601d88c051c7d4a1c2f7742'
    auth_token = '19a3d6f76b93fda3a0f16ccb388ac648'
    @client = Twilio::REST::Client.new(account_sid, auth_token)
    message = @client.messages.create(
                             body: 'MENSAGEM DE '+nome.upcase+": "+mensagem.downcase,
                             from: 'whatsapp:+14155238886',
                             to: 'whatsapp:+556681369818'
                           )
    puts message.sid
  end
end

app/helpers/whatsapp_infos_helper.rb
module WhatsappInfosHelper
end

app/views/boletins/_form.html.erb
<%= form_with(model: boletim, local: true) do |form| %>
  <% if boletim.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(boletim.errors.count, "error") %> prohibited this boletim from being saved:</h2>

      <ul>
      <% boletim.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boletins/edit.html.erb
<h1>Editing Boletim</h1>

<%= render 'form', boletim: @boletim %>

<%= link_to 'Show', @boletim %> |
<%= link_to 'Back', boletins_path %>

app/views/boletins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boletins</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boletins.each do |boletim| %>
      <tr>
        <td><%= boletim.email %></td>
        <td><%= link_to 'Show', boletim %></td>
        <td><%= link_to 'Edit', edit_boletim_path(boletim) %></td>
        <td><%= link_to 'Destroy', boletim, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Boletim', new_boletim_path %>

app/views/boletins/new.html.erb
<h1>New Boletim</h1>

<%= render 'form', boletim: @boletim %>

<%= link_to 'Back', boletins_path %>

app/views/boletins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @boletim.email %>
</p>

<%= link_to 'Edit', edit_boletim_path(@boletim) %> |
<%= link_to 'Back', boletins_path %>

app/views/pages/about/_about-info.html.erb
                      <h2>Ferramentas, ração, sementes e diversos produtos para o amigo fazendeiro.</h2>

                              <figure>
                                   <span><i class="fa fa-users"></i></span>
                                   <figcaption>
                                        <h3>Bom atendimento</h3>
                                        <p>Empresa de confiança. Com os melhores produtos e o apoio de uma equipe preparada.</p>
                                   </figcaption>
                              </figure>

                              <figure>
                                   <span><i class="fa fa-thumbs-up"></i></span>
                                   <figcaption>
                                        <h3>Produtos de Qualidade</h3>
                                        <p>Trabalhamos com grandes marcas já consagrada no mercado, para melhor lhe atender.</p>
                                   </figcaption>
                              </figure>

                              <figure>
                                   <span><i class="fa fa-sort-amount-asc"></i></span>
                                   <figcaption>
                                        <h3>Preço Baixo</h3>
                                        <p>Grande preocupação com nossos clientes, oferecendo produtos com preços que cabe no seu bolso.</p>
                                   </figcaption>
                              </figure>

app/views/pages/about/_entry-form.html.erb
<%= flash_messages if defined? (flash[:success]["mensagem"].size) %>
<form action="whatsapp/index" method="post">
	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	<h4 style="color:#fff">Envie uma mensagem para nosso Whatsapp!</h4>
	<input type="text" name="nome" class="form-control" placeholder="Nome completo" required="">
	<input type="text" name="mensagem" class="form-control" placeholder="Mensagem" required="">
	<!-- <input type="email" name="email" class="form-control" placeholder="Endereço de e-mail" required=""> -->
	<!-- <input type="password" name="password" class="form-control" placeholder="senha" required=""> -->
	<button class="submit-btn form-control" id="form-submit">Enviar</button>
</form>

app/views/pages/contact/_index.html.erb
<div class="container">
     <div class="row">
          <div class="col-md-6 col-sm-12">
               <%= flash_messages if defined? (flash[:success]["Contato"].size) %>
               <form id="contact-form" role="form" action="/contatos" method="post">
                    <%= hidden_field_tag :authenticity_token, form_authenticity_token %> 
                    <div class="section-title">
                         <h2>Contato <small>Entre em contato, que logo responderemos!</small></h2>
                    </div>
                    <div class="col-md-12 col-sm-12">
                         <input type="text" class="form-control" placeholder="Escreva seu nome completo" name="contato[nome]" required="">
                         <input type="email" class="form-control" placeholder="Escreva seu endereço de email" name="contato[email]" required="">
                         <textarea class="form-control" rows="6" placeholder="Escreva sua mensagem" name="contato[mensagem]" required=""></textarea>
                    </div>
                    <div class="col-md-4 col-sm-12">
                         <input type="submit" class="form-control" name="Enviar mensagem" value="Enviar Mensagem">
                    </div>
               </form>
          </div>
          <div class="col-md-6 col-sm-12">
               <div class="contact-image">
                    <img src="images/contact-image.jpg" class="img-responsive" alt="Smiling Two Girls">
               </div>
          </div>
     </div>
</div>

app/views/pages/courses/_index.html.erb
<div class="container">
<div class="row">
     <div class="col-md-12 col-sm-12">
          <div class="section-title">
               <h2>PRODUTOS <small>em destaque.</small></h2> 
          </div>
          <div class="owl-carousel owl-theme owl-courses">
               <%= render partial: "pages/courses/produto",:locals => {:p => 1} %>
          </div>
          <div class="owl-carousel owl-theme owl-courses">
               <%= render partial: "pages/courses/produto",:locals => {:p => 2} %>
          </div>
     </div>
</div>

app/views/pages/courses/_produto.html.erb
<% @produtos = @primeira_parte_em_produtos if p == 1 %>   
<% @produtos = @segunda_parte_em_produtos if p == 2 %>  
<% @produtos.each do |produto| %>
<div class="col-md-4 col-sm-4">
     <div class="item">
          <div class="courses-thumb">
               <div class="courses-top">
                    <div class="courses-image">
                              <%= cl_image_tag(produto.image.key,class:"img-responsive",:transformation=>[{:width=>350,:height=>250,:crop=>"fill"}]) 
                              %>
                    </div>
                    <div class="courses-date">
                         <!-- ################################################
                          <span><i class="fa fa-calendar"></i> </span>
                         <span><i class="fa fa-clock-o"></i> </span> 
                         ##################################################### -->
                    </div>
               </div>

               <div class="courses-detail">
                    <h3><a href=""><%= produto.name.titleize %></a></h3>
                    <p><%= produto.descricao %></p>
               </div>

               <div class="courses-info">
                    <div class="courses-author">
                         <%= cl_image_tag(produto.image.key,class:"img-responsive", :transformation=>[{:width=>50,:height=>50,:crop=>"fill"}]) 
                         %>
                         <span><%= produto.quantidade %>: </span>
                    </div>
                    <div class="courses-price">
                         <a href=""><span>R$<%= produto.valor %></span></a>
                    </div>
               </div>
          </div>
     </div>
</div>
<% end %>

app/views/pages/feature/_index.html.erb
<div class="container">
     <div class="row">

          <div class="col-md-4 col-sm-4">
               <div class="feature-thumb">
                    <span><i class="fa fa-shopping-cart"></i></i></i></span>
                    <h3>Venda de Tambores</h3>
                    <p>Cocheiras, cochos, bebedouros, churrasqueiras, grelhas, lixeiras, baldes e rações.</p>
               </div>
          </div>

          <div class="col-md-4 col-sm-4">
               <div class="feature-thumb">
                    <span><i class="fa fa-sun-o"></i></span>
                    <h3>Sementes de pastagens</h3>
                    <p>Tambores Nogueira tem sempre a melhor opção em sementes. São sementes puras, polimerizadas, tratadas e diluídas com cristais de cálcio, tendo atestado de garantia e boletim de análise. O que garante o plantio de um produto de qualidade comprovada.</p>
               </div>
          </div>

          <div class="col-md-4 col-sm-4">
               <div class="feature-thumb">
                    <span><i class="fa fa-wrench"></i></span>
                    <h3>Ferramentas</h3>
                    <p>Temos uma ampla linha de ferramentas motorizadas portáteis, destinados as áreas florestal, agropecuário, jardinagem profissional, limpeza e conservação, construção civil e uso ocasional.</p>
               </div>
          </div>

     </div>
</div>

app/views/pages/footer/_index.html.erb
<div class="container">
     <div class="row">
          <div class="col-md-4 col-sm-6">
               <div class="footer-info">
                    <div class="section-title">
                         <h2 style="color:white">Tambores Nogueira</h2>
                    </div>
                    <address>
                         <p>Rua 31 de Março Nº 1.290 - Centro - Campinápolis-MT</p>
                    </address>

<!--                     <ul class="social-icon">
                         <li><a href="#" class="fa fa-facebook-square" attr="facebook icon"></a></li>
                         <li><a href="#" class="fa fa-twitter"></a></li>
                         <li><a href="#" class="fa fa-instagram"></a></li>
                    </ul>
 -->
                    <div class="copyright-text"> 
                         <p>campinapolis.com &copy; 2019</p>
                         <!-- <p>Desenvolvido: <a rel="nofollow" href="http://campinapolis.com" title="Portal" target="_parent">Eudes & Carlos</a></p> -->
                    </div>
               </div>
          </div>

          <div class="col-md-4 col-sm-6">
               <div class="footer-info">
                    <div class="section-title">
                         <h2 style="color:white">Contato</h2>
                    </div>
                    <address>
                         <p>(66) 3437-1341, (66) 98115-8518</p>
                         <p><a href="email para tamboresnogueira@hotmail.com">tamboresnogueira@hotmail.com</a></p>
                    </address>

                    <div class="footer_menu">
                         <h2 style="color:white">Links</h2>
                         <ul>
                              <li><a href="Https://campinapolis.com">Campinapolis.com</a></li>
                                        <!-- <li><a href="Http://www.youtube.com">Youtube</a></li>
                                        <li><a href="Http://www.facebook.com">Facebook</a></li>
                                        <li><a href="Http://www.google.com.br">Google</a></li> -->
                                   </ul>
                              </div>
                         </div>
                    </div>

                    <div class="col-md-4 col-sm-12">
                         <div class="footer-info newsletter-form">
                              <div class="section-title">
                                   <h2 style="color:white">Boletim Informativo</h2>
                              </div>
                              <div>
                                   <div class="form-group">
                                        <form action="/boletins" method="post">
                                             <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                                             <input type="email" class="form-control" placeholder="Coloque seu email" name="boletim[email]" id="email" required="">
                                             <input type="submit" class="form-control" name="submit" id="form-submit" value="Enviar me">
                                        </form>
                                        <span><sup>*</sup> Não enviamos spam para seu email.</span>
                                   </div>
                              </div>
                         </div>
                    </div>
                    
               </div>
          </div>

app/views/pages/home/_index.html.erb
<div id="comslider_in_point_1778442"></div>
<script type="text/javascript">
var oCOMScript1778442=document.createElement('script');
oCOMScript1778442.src="comslider1778442/comsliderd.js?timestamp=1551045594";
oCOMScript1778442.type='text/javascript';
document.getElementsByTagName("head").item(0).appendChild(oCOMScript1778442);
</script>
<!-- HOME -->
<!-- <section id="home">
    <div class="row">  
     <div class="owl-carousel owl-theme home-slider">
          <div class="item item-first">
               <div class="caption">
                    <div class="container">
                         <div class="col-md-6 col-sm-12">
                              <h1>Ferramentas</h1>
                              <h3>Peças, ferramentas e maquinários.</h3>
                              <a href="#feature" class="section-btn btn btn-default smoothScroll">PRODUTOS</a>
                         </div>
                    </div>
               </div>
          </div>

          <div class="item item-second">
               <div class="caption">
                    <div class="container">
                         <div class="col-md-6 col-sm-12">
                              <h1>Tambores</h1>
                              <h3>Variedades em produtos em tambores.</h3>
                              <a href="#courses" class="section-btn btn btn-default smoothScroll">PRODUTOS</a>
                         </div>
                    </div>
               </div>
          </div>

          <div class="item item-third">
               <div class="caption">
                    <div class="container">
                         <div class="col-md-6 col-sm-12">
                              <h1>Rações</h1>
                              <h3>Variedades em rações.<a href="https://campinapolis.com" target="_parent"></a></h3>
                              <a href="#contact" class="section-btn btn btn-default smoothScroll">MENSAGEM</a>
                         </div>
                    </div>
               </div>
          </div>
     </div>
</div>
</section>

 -->

app/views/pages/team/_index.html.erb
<div class="container">
     <div class="row">

          <div class="col-md-12 col-sm-12">
               <div class="section-title">
                    <h2>Equipe <small>Nosso Time!</small></h2>
               </div>
          </div>

          <div class="col-md-4 col-sm-6">
               <div class="team-thumb">
                    <div class="team-image">
                         <img src="images/author-image1.jpg" class="img-responsive" alt="">
                    </div>
                    <div class="team-info">
                         <h3>José Lazaro Nogueira Neto</h3>
                         <span>Empresário</span>
                    </div>
                    <ul class="social-icon">
                         <li><a href="https://www.facebook.com/leonardo.padua.79" class="fa fa-facebook-square" attr="facebook icon"></a></li>
                    </ul>
               </div>
          </div>

          <div class="col-md-4 col-sm-6">
               <div class="team-thumb">
                    <div class="team-image">
                         <img src="images/author-image2.jpg" class="img-responsive" alt="">
                    </div>
                    <div class="team-info">
                         <h3>Raquel</h3>
                         <span>Empresária</span>
                    </div>
                    <ul class="social-icon">
                         <li><a href="https://www.facebook.com/profile.php?id=100011347917864" class="fa fa-facebook-square" attr="facebook icon"></a></li>
                    </ul>
               </div>
          </div>

          <!-- <div class="col-md-3 col-sm-6"> -->
                         <!-- <div class="team-thumb">
                              <div class="team-image">
                                   <img src="images/author-image3.jpg" class="img-responsive" alt="">
                              </div>
                              <div class="team-info">
                                   <h3>Maria</h3>
                                   <span>Secretária.</span>
                              </div>
                              <ul class="social-icon">
                                   <li><a href="#" class="fa fa-twitter"></a></li>
                                   <li><a href="#" class="fa fa-envelope-o"></a></li>
                                   <li><a href="#" class="fa fa-linkedin"></a></li>
                              </ul>
                         </div> -->
                         <!-- </div> -->

                         <div class="col-md-4 col-sm-6">
                              <div class="team-thumb">
                                   <div class="team-image">
                                        <img src="images/author-image4.jpg" class="img-responsive" alt="">
                                   </div>
                                   <div class="team-info">
                                        <h3>Débora</h3>
                                        <span>Atendente.</span>
                                   </div>
<!--                                    <ul class="social-icon">
                                        <li><a href="#" class="fa fa-twitter"></a></li>
                                   </ul>
 -->                              </div>
                         </div>

                    </div>
               </div>

app/views/whatsapp_infos/_form.html.erb
<%= form_with(model: whatsapp_info, local: true) do |form| %>
  <% if whatsapp_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(whatsapp_info.errors.count, "error") %> prohibited this whatsapp_info from being saved:</h2>

      <ul>
      <% whatsapp_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :to %>
    <%= form.text_field :to %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/whatsapp_infos/edit.html.erb
<h1>Editing Whatsapp Info</h1>

<%= render 'form', whatsapp_info: @whatsapp_info %>

<%= link_to 'Show', @whatsapp_info %> |
<%= link_to 'Back', whatsapp_infos_path %>

app/views/whatsapp_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Whatsapp Infos</h1>

<table>
  <thead>
    <tr>
      <th>To</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @whatsapp_infos.each do |whatsapp_info| %>
      <tr>
        <td><%= whatsapp_info.to %></td>
        <td><%= link_to 'Show', whatsapp_info %></td>
        <td><%= link_to 'Edit', edit_whatsapp_info_path(whatsapp_info) %></td>
        <td><%= link_to 'Destroy', whatsapp_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Whatsapp Info', new_whatsapp_info_path %>

app/views/whatsapp_infos/new.html.erb
<h1>New Whatsapp Info</h1>

<%= render 'form', whatsapp_info: @whatsapp_info %>

<%= link_to 'Back', whatsapp_infos_path %>

app/views/whatsapp_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>To:</strong>
  <%= @whatsapp_info.to %>
</p>

<%= link_to 'Edit', edit_whatsapp_info_path(@whatsapp_info) %> |
<%= link_to 'Back', whatsapp_infos_path %>